name: Run job scraper and Algolia loader

on:
  schedule:
    # Run the job at 8:00 AM every Monday and Thursday in UTC time
    - cron: '0 10 * * 1,4'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the greenhouseScrape.py script
      - name: Run greenhouseScrape.py
        env:
          db_url: DB_URL
        run: python3 greenhouseScrape.py

      # Run the algolia_load.py script
      - name: Run algolia_load.py
        run: python3 algolia_load.py
        env:
          ALGOLIA_APP_ID: your_algolia_app_id
          ALGOLIA_ADMIN_KEY: your_algolia_admin_key
